### PR TITLE
Only for Qt6

### PR DESCRIPTION
**Pull request by tsujan**
Removed all traces of Qt5/Qt4 and used C++17.

### CODE REVIEW

**Comment by yan12125** [comment]
Is it better to call the library as something like `libdbusmenu-lxqt6.so` instead of `libdbusmenu-lxqt.so`? Perhaps one day, we need to allow Qt 6 and Qt 7 variants of this library to co-exist.

**Comment by tsujan** [comment]
Yes, it occurred to me too, but I thought, "We don't use `lxqt6` anywhere; and we'll find a solution when Qt7 comes" ;)

**Comment by yan12125** [comment]
> and we'll find a solution when Qt7 comes" ;)

Wise :D

**Comment by tsujan** [comment]
Since `lxqt6`can be misleading (LXQt doesn't have a version 6), we could have named the so file as `libdbusmenu-lxqt-qt6.so`, but, IMHO, there's no need to this long name now, because we don't have a Qt5 version of it.

Later, when Qt7 comes, we could use `libdbusmenu-lxqt-qt7.so`.

**Comment by yan12125** [comment]
That's a good idea.

**Comment by yan12125** [comment]
Several files still mention dbusmenu-qt:
```
grep -r dbusmenu-qt
grep: .git/objects/pack/pack-95820f7bfdcf2fe09786cfa913e89d925593bb85.pack: binary file matches
grep: .git/index: binary file matches
CMakeLists.txt:project(dbusmenu-qt)
CMakeLists.txt:configure_file(dbusmenu-qt.pc.in ${CMAKE_BINARY_DIR}/dbusmenu-lxqt.pc @ONLY)
CMakeLists.txt:# Generate dbusmenu-qt-config* files
CMakeLists.txt:    dbusmenu-qt-config.cmake.in
CMakeLists.txt:# Install dbusmenu-qt-config* files
Doxyfile.in:PROJECT_NAME           = dbusmenu-qt
README:>LXQt fork of [desktop-app/libdbusmenu-qt](https://github.com/desktop-app/libdbusmenu-qt)
README:https://launchpad.net/libdbusmenu-qt
README:http://gitorious.org/dbusmenu/dbusmenu-qt
RELEASE_CHECK_LIST:  lp-project-upload libdbusmenu-qt $tag libdbusmenu-qt-$tag.tar.bz2
src/CMakeLists.txt:# Make sure linking to the target adds dbusmenu-qt install directory
src/dbusmenu_export.h:/* This file is part of the dbusmenu-qt library
src/dbusmenu_p.cpp:/* This file is part of the dbusmenu-qt library
src/dbusmenu_p.h:/* This file is part of the dbusmenu-qt library
src/dbusmenu_version.h.in:// Use this macro to add code which depends on a minimum version of dbusmenu-qt
src/dbusmenuexporter.cpp:/* This file is part of the dbusmenu-qt library
src/dbusmenuexporter.cpp:// cf. https://bugs.launchpad.net/libdbusmenu-qt/+bug/793339
src/dbusmenuexporter.h:/* This file is part of the dbusmenu-qt library
src/dbusmenuexporterdbus_p.cpp:/* This file is part of the dbusmenu-qt library
src/dbusmenuexporterdbus_p.h:/* This file is part of the dbusmenu-qt library
src/dbusmenuexporterprivate_p.h:/* This file is part of the dbusmenu-qt library
src/dbusmenuimporter.cpp:/* This file is part of the dbusmenu-qt library
src/dbusmenuimporter.h:/* This file is part of the dbusmenu-qt library
src/dbusmenuimporter.h:     * dbusmenu-qt 0.3.x. New code should use updateMenu() and menuUpdated()
src/dbusmenushortcut_p.cpp:/* This file is part of the dbusmenu-qt library
src/dbusmenushortcut_p.cpp:      // cf https://bugs.launchpad.net/libdbusmenu-qt/+bug/712565
src/dbusmenushortcut_p.h:/* This file is part of the dbusmenu-qt library
src/dbusmenutypes_p.cpp:/* This file is part of the dbusmenu-qt library
src/dbusmenutypes_p.h:/* This file is part of the dbusmenu-qt library
src/debug_p.h:/* This file is part of the dbusmenu-qt library
src/utils.cpp:/* This file is part of the dbusmenu-qt library
src/utils_p.h:/* This file is part of the dbusmenu-qt library
tests/dbusmenuexportertest.cpp:/* This file is part of the dbusmenu-qt library
tests/dbusmenuexportertest.cpp:static const char *TEST_SERVICE = "org.kde.dbusmenu-qt-test";
tests/dbusmenuexportertest.h:/* This file is part of the dbusmenu-qt library
tests/dbusmenuimportertest.cpp:/* This file is part of the dbusmenu-qt library
tests/dbusmenuimportertest.cpp:static const char *TEST_SERVICE = "com.canonical.dbusmenu-qt-test";
tests/dbusmenuimportertest.h:/* This file is part of the dbusmenu-qt library
tests/dbusmenushortcuttest.cpp:/* This file is part of the dbusmenu-qt library
tests/dbusmenushortcuttest.h:/* This file is part of the dbusmenu-qt library
tests/slowmenu.cpp:/* This file is part of the dbusmenu-qt library
tests/slowmenu.cpp:static const char *TEST_SERVICE = "org.kde.dbusmenu-qt-test";
tests/slowmenu.h:/* This file is part of the dbusmenu-qt library
tests/testutils.cpp:/* This file is part of the dbusmenu-qt library
tests/testutils.h:/* This file is part of the dbusmenu-qt library
tools/testapp/main.cpp:/* This file is part of the dbusmenu-qt library
```
In my opinion it's better to update filenames and comments in cmake files to use dbusmenu-lxqt, as installed filenames are changed in this PR. It's fine to leave other files as-is.

**Comment by yan12125** [comment]
Thanks for the update. Sorry I missed another pattern last time - some of `DBUSMENUQT_*` macros in src/dbusmenu_version.h.in should probably changed to something like `DBUSMENU_LXQT_*` as well.

**Comment by tsujan** [comment]
Good point. Thanks!

For being consistent with other parts, I think `DBUSMENUQT` should be changed to `DBUSMENULXQT` (without an extra underline).

**Comment by yan12125** [comment]
> without an extra underline

That's fine~

**Comment by tsujan** [comment]
Done. I think there's no trace of it anymore.

Can this be merged?

**Comment by tsujan** [comment]
@yan12125 
Thanks!

The next step is trying to use it in the Qt6 branch of `lxqt-qtplugin`, instead of `dbusmenu-qt6`.

**Comment by yan12125** [comment]
There is one more step: https://github.com/lxqt/libdbusmenu-lxqt/pull/5

**Comment by tsujan** [comment]
> There is one more step: #5

Will check it soon.

**Pull request merged**
