### PR TITLE
Renamed README;compiling instructions

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Comment by yan12125** [comment]
Sorry, I though https://github.com/lxqt/libdbusmenu-lxqt/pull/3 was complete. Let's mark the pull request as a draft to avoid accidental merges.

**Comment by tsujan** [comment]
@yan12125 
An Arch package for `libdbusmenu-lxqt` may be needed.

Last night, Qt6 was upgraded from 6.6.0 to 6.6.1 here, and the tray icons of Qt6-based apps didn't have context menus after that — whether under LXQt+X11 or under LXQt+Wayland (with Waybar). The issue was fixed after I made the Qt6 branch of `lxqt-qtplugin` depend on `libdbusmenu-lxqt` (haven't added a commit yet).

BTW, ` libdbusmenu-qt6` couldn't be compiled anymore, while `libdbusmenu-lxqt` has no problem with Qt 6.6.1.

**Comment by yan12125** [comment]
Thanks for the information, but I don't have time for a new package this week. https://aur.archlinux.org/packages/libdbusmenu-lxqt-git may be useful for now.

**Comment by tsujan** [comment]
>  https://aur.archlinux.org/packages/libdbusmenu-lxqt-git may be useful for now.

Oh, I didn't know about it. Thanks! Yes, it'll do the job :)

Anyway, for a long time, I wanted to make the Qt6-based `lxqt-qtplugin` depend on `libdbusmenu-lxqt` but delayed it, assuming that it would be a lot work. It was a piece of cake :)

**Comment by tsujan** [comment]
BTW, I think `libdbusmenu-qt6` can be removed.

**Comment by tsujan** [comment]
> That package wasn't added by me.

Sorry, my mistake; I'd assumed it was for LXQt.

So, it just needs to be replaced by [libdbusmenu-lxqt-git](https://aur.archlinux.org/packages/libdbusmenu-lxqt-git) in the dependencies list of [lxqt-qt6plugin-git](https://aur.archlinux.org/packages/lxqt-qt6plugin-git).

**Comment by yan12125** [comment]
> So, it just needs to be replaced by [libdbusmenu-lxqt-git](https://aur.archlinux.org/packages/libdbusmenu-lxqt-git) in the dependencies list of [lxqt-qt6plugin-git](https://aur.archlinux.org/packages/lxqt-qt6plugin-git).

Done! I didn't test the tray icon though - I don't have a Qt 6 application using a tray icon.

**Comment by stefonarch** [comment]
I've tested both with strawberry and telegram which were missing  both right click menu.

**Comment by tsujan** [comment]
@yan12125 , thanks!

> I don't have a Qt 6 application using a tray icon.

I have FeatherNotes, QBittorrent, and Telegram. After the upgrade to Qt 6.6.1 (last night for me), they lost their right click menus; now those menus are back, whether under X11 or Wayland + LXQt.

**Comment by yan12125** [comment]
> I've tested both with strawberry and telegram which were missing both right click menu.

Still an issue after rebuilding the latest lxqt-qtplugin (https://github.com/lxqt/lxqt-qtplugin/commit/8e8a2b324152f0102300a06888ce3cc511621284) with libdbusmenu-lxqt?

And yes, I forgot telegram is a Qt 6 application - I usually use web.telegram.org nowadays.

**Comment by tsujan** [comment]
> Still an issue after rebuilding the latest lxqt-qtplugin ... with libdbusmenu-lxqt?

None.

This was what happened (in case I wasn't clear enough):

 1. Everything was OK before Qt 6.6.1.
 2. When Qt 6.6.1 came here, Qt6 apps lost their right click menus in their tray icons on X11 and Wayland.
 3. I got suspicious of `libdbusmenu-qt6` and replaced it with `libdbusmenu-lxqt` in `lxqt-qtplugin` (https://github.com/lxqt/lxqt-qtplugin/pull/74/commits/8e8a2b324152f0102300a06888ce3cc511621284).
 4. The issue was fixed.
 5. Later I found out that `libdbusmenu-qt6` couldn't be compiled against Qt 6.6.1, but that wasn't our problem anymore.

**Comment by yan12125** [comment]
Great! Thank you both for confirmation.

**Comment by tsujan** [comment]
The `Author` can be removed, IMO. The source of forking has already been mentioned, and only LXQt is responsible for libdbusmenu-lxqt.

**Comment by stefonarch** [comment]
Done and added preliminary package info as in other repos.

**Comment by tsujan** [comment]
Ship it.

**Comment by luis-pereira** [comment]
BTW, can someone take a look at https://github.com/lxqt/libdbusmenu-lxqt/pull/12 ?

**Comment by tsujan** [comment]
> BTW, can someone take a look at https://github.com/lxqt/libdbusmenu-lxqt/pull/12 ?

Sure; it's in my TODO list.

**Pull request merged**
